// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSixtarScorecard;

#nullable disable

namespace SimpleSixtarScorecard.Migrations
{
    [DbContext(typeof(ResultContext))]
    [Migration("20251002081244_ResultsTableName")]
    partial class ResultsTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107");

            modelBuilder.Entity("SimpleSixtarScorecard.ReleasesEtag", b =>
                {
                    b.Property<string>("Etag")
                        .HasColumnType("TEXT")
                        .HasColumnName("Etag");

                    b.HasKey("Etag");

                    b.ToTable("EtagSingle", (string)null);
                });

            modelBuilder.Entity("SimpleSixtarScorecard.Result", b =>
                {
                    b.Property<string>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SongId")
                        .HasJsonPropertyName("songid");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT")
                        .HasColumnName("Mode")
                        .HasJsonPropertyName("mode");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT")
                        .HasColumnName("Difficulty")
                        .HasJsonPropertyName("difficulty");

                    b.Property<bool>("FullCombo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FullCombo")
                        .HasJsonPropertyName("fullcombo");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Score")
                        .HasJsonPropertyName("score");

                    b.HasKey("SongId", "Mode", "Difficulty");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
