// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSixtarScorecard;

#nullable disable

namespace SimpleSixtarScorecard.Migrations
{
    [DbContext(typeof(ResultContext))]
    [Migration("20250902080713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("SimpleSixtarScorecard.ReleasesEtag", b =>
                {
                    b.Property<string>("Etag")
                        .HasColumnType("TEXT")
                        .HasColumnName("etag");

                    b.HasKey("Etag");

                    b.ToTable("ReleasesEtag", (string)null);
                });

            modelBuilder.Entity("SimpleSixtarScorecard.Result", b =>
                {
                    b.Property<string>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("song_id");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT")
                        .HasColumnName("difficulty");

                    b.Property<bool>("FullCombo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("full_combo");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.HasKey("SongId", "Mode", "Difficulty");

                    b.ToTable("Result", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
