// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSixtarScorecard;

#nullable disable

namespace SimpleSixtarScorecard.Migrations
{
    [DbContext(typeof(ResultsContext))]
    partial class ResultsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SimpleSixtarScorecard.Result", b =>
                {
                    b.Property<string>("SongId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SongId")
                        .HasJsonPropertyName("songid");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT")
                        .HasColumnName("Mode")
                        .HasJsonPropertyName("mode");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT")
                        .HasColumnName("Difficulty")
                        .HasJsonPropertyName("difficulty");

                    b.Property<bool>("FullCombo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FullCombo")
                        .HasJsonPropertyName("fullcombo");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Score")
                        .HasJsonPropertyName("score");

                    b.HasKey("SongId", "Mode", "Difficulty");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
